---
kind: Template
apiVersion: template.openshift.io/v1
labels:
  template: ${app}-template
  appcode: ${appcode}
metadata:
  name: ${app}
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${app}
  spec:
    completionDeadlineSeconds: 1200
    failedBuildsHistoryLimit: 5
    runPolicy: Serial
    source:
      git:
        uri: 'https://github.com/wes-spinks/miro-team-create.git'
        ref: ${tag}
      secrets:
        - secret:
            name: ca-crt
      sourceSecret:
        name: wsgithub
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
        forcePull: true
        env:
          - name: APP_ROOT
            value: ${approot}
          - name: GIT_SSL_NO_VERIFY
            value: 'true'
          - name: APP_HOME
            value: ${approot}
          - name: APP_FILE
            value: 'app.py'
          - name: PIP_INDEX_URL
            value: "https://nexus.spinks.work/repository/pypi-all/simple"
          - name: PIP_TRUSTED_HOST
            value: "nexus.spinks.work"
    output:
      imageLabels:
      - name: work.spinks.appcode
        value: ${appcode}
      to:
        kind: DockerImage
        name: 'images.spinks.work/auto/${app}:${tag}'
      pushSecret:
        name: images-push-sec
    triggers:
      - type: ConfigChange
- apiVersion: v1
  type: kubernetes.io/basic-auth
  kind: Secret
  metadata:
    name: wsgithub
  stringData:
    username: wes-spinks 
  data:
    password: ${PullSecret}
- apiVersion: v1
  kind: Secret
  metadata:
    name: ca-crt
  data:
    ca.crt: ${ItCA}
parameters:
  - name: app
    displayName: App
    description: The label for objects created by template
    required: true
    value: miro-team-create
  - name: appcode
    required: true
    value: MTC01
  - name: tag
    displayName: ImageTag
    description: The registry image ref
    required: true
    value: main
  - name: approot
    displayName: AppRoot
    description: The application root dir
    required: true
    value: /opt/app-root
  - name: PullSecret
    displayName: PullSecret
    required: true
  - name: ItCA
    displayName: ItCA
    required: true
